spring:
  application:
    name: naming-service
  config:
    import: "optional:configserver:"
  cloud:
    service-registry:
      auto-registration:
        enabled: false
server:
  port: 8761
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
management:
  tracing:
    sampling:
      probability: 1.0
  export:
    zipkin:
      endpoint: http://localhost:9411/api/v2/spans

