spring:
  application:
    name: conversao-ativa
  config:
    import: "optional:configserver:"
server:
  port: 8100
debug: true
management:
  tracing:
    sampling:
      probability: 1.0
  export:
    zipkin:
      endpoint: http://localhost:9411/api/v2/spans
